import {Router} from 'express';
import {z} from 'zod';
import {prisma} from '../lib/prisma.js';
import {nextFolio as nextSequenceFolio} from '../services/sequence.js';
import {requireAuth} from '../middleware/auth.js';
import {idempotency} from '../middleware/idempotency.js';
import {requirePermission} from '../middleware/permissions.js';
const router=Router();router.use(requireAuth);
router.use(idempotency());
const invoiceSchema=z.object({customerId:z.string().min(1),invoiceNumber:z.string().trim().min(1).max(80),issueDate:z.coerce.date(),dueDate:z.coerce.date(),currency:z.string().trim().length(3).default('MXN'),subtotal:z.coerce.number().min(0),taxAmount:z.coerce.number().min(0),total:z.coerce.number().positive(),notes:z.string().trim().optional().nullable()});
const paymentSchema=z.object({amount:z.coerce.number().positive(),paymentDate:z.coerce.date(),method:z.string().trim().min(2).max(50),reference:z.string().trim().optional().nullable(),notes:z.string().trim().optional().nullable()});
const computed=i=>{const balance=Number(i.total)-Number(i.paidAmount);const overdue=balance>0&&new Date(i.dueDate)<new Date()&&i.status!=='CANCELLED';return {...i,balance,displayStatus:overdue?'OVERDUE':i.status}};
async function folio(companyId,tx=prisma){const y=String(new Date().getFullYear());return nextSequenceFolio({companyId,scope:'customer-payment',prefix:'COB',digits:4,period:y,model:'customerPayment',where:{companyId,folio:{startsWith:`COB-${y}-`}},db:tx})}
router.get('/',requirePermission('accounts_receivable.read'),async(req,res,next)=>{try{const invoices=await prisma.accountsReceivable.findMany({where:{companyId:req.auth.companyId},include:{customer:true,payments:{orderBy:{paymentDate:'desc'}}},orderBy:[{dueDate:'asc'},{createdAt:'desc'}]});const rows=invoices.map(computed);const metrics=rows.reduce((a,r)=>{if(r.status!=='CANCELLED'){a.total+=Number(r.total);a.collected+=Number(r.paidAmount);a.balance+=r.balance;if(r.displayStatus==='OVERDUE')a.overdue+=r.balance}return a},{total:0,collected:0,balance:0,overdue:0});res.json({ok:true,invoices:rows,metrics})}catch(e){next(e)}});
router.get('/catalogs',requirePermission('accounts_receivable.read'),async(req,res,next)=>{try{const customers=await prisma.customer.findMany({where:{companyId:req.auth.companyId,active:true},orderBy:{legalName:'asc'}});res.json({ok:true,customers})}catch(e){next(e)}});
router.post('/',requirePermission('accounts_receivable.manage'),async(req,res,next)=>{try{const p=invoiceSchema.safeParse(req.body);if(!p.success)return res.status(400).json({ok:false,message:p.error.issues[0]?.message??'Datos inválidos'});if(p.data.dueDate<p.data.issueDate)return res.status(400).json({ok:false,message:'La fecha de vencimiento no puede ser anterior a la fecha de emisión'});const customer=await prisma.customer.findFirst({where:{id:p.data.customerId,companyId:req.auth.companyId}});if(!customer)return res.status(404).json({ok:false,message:'Cliente no encontrado'});const invoice=await prisma.accountsReceivable.create({data:{...p.data,currency:p.data.currency.toUpperCase(),companyId:req.auth.companyId,createdById:req.auth.sub}});await prisma.auditLog.create({data:{userId:req.auth.sub,action:'CREATE',entity:'AccountsReceivable',entityId:invoice.id,description:`Factura ${invoice.invoiceNumber} registrada`,ipAddress:req.ip}});res.status(201).json({ok:true,invoice:computed(invoice)})}catch(e){if(e.code==='P2002')return res.status(409).json({ok:false,message:'Esta factura ya fue registrada para el cliente'});next(e)}});
router.post('/:id/payments',requirePermission('accounts_receivable.collect'),async(req,res,next)=>{try{const p=paymentSchema.safeParse(req.body);if(!p.success)return res.status(400).json({ok:false,message:p.error.issues[0]?.message??'Datos inválidos'});const invoice=await prisma.accountsReceivable.findFirst({where:{id:req.params.id,companyId:req.auth.companyId}});if(!invoice)return res.status(404).json({ok:false,message:'Factura no encontrada'});if(invoice.status==='CANCELLED')return res.status(400).json({ok:false,message:'No se puede cobrar una factura cancelada'});const balance=Number(invoice.total)-Number(invoice.paidAmount);if(p.data.amount>balance+.001)return res.status(400).json({ok:false,message:'El cobro supera el saldo pendiente'});const result=await prisma.$transaction(async tx=>{const f=await folio(req.auth.companyId,tx);const payment=await tx.customerPayment.create({data:{...p.data,companyId:req.auth.companyId,accountsReceivableId:invoice.id,createdById:req.auth.sub,folio:f}});const paidAmount=Number(invoice.paidAmount)+p.data.amount;const status=paidAmount>=Number(invoice.total)-.001?'PAID':'PARTIALLY_PAID';const updated=await tx.accountsReceivable.update({where:{id:invoice.id},data:{paidAmount,status},include:{customer:true,payments:{orderBy:{paymentDate:'desc'}}}});await tx.auditLog.create({data:{userId:req.auth.sub,action:'COLLECTION',entity:'AccountsReceivable',entityId:invoice.id,description:`Cobro ${f} aplicado por ${p.data.amount}`,ipAddress:req.ip}});return {payment,invoice:computed(updated)}});res.status(201).json({ok:true,...result})}catch(e){next(e)}});
router.patch('/:id/cancel',requirePermission('accounts_receivable.manage'),async(req,res,next)=>{try{const invoice=await prisma.accountsReceivable.findFirst({where:{id:req.params.id,companyId:req.auth.companyId}});if(!invoice)return res.status(404).json({ok:false,message:'Factura no encontrada'});if(Number(invoice.paidAmount)>0)return res.status(400).json({ok:false,message:'No se puede cancelar una factura con cobros'});const updated=await prisma.accountsReceivable.update({where:{id:invoice.id},data:{status:'CANCELLED'}});res.json({ok:true,invoice:computed(updated)})}catch(e){next(e)}});
export default router;
