import {Router} from 'express';
import {z} from 'zod';
import {prisma} from '../lib/prisma.js';
import {requireAuth} from '../middleware/auth.js';
import {requirePermission} from '../middleware/permissions.js';
import {emitIntegrationEventAsync} from '../services/integrationEvents.js';
import {syncBusinessParties} from '../services/businessParties.js';

const router = Router();
router.use(requireAuth);
const schema = z.object({code:z.string().trim().min(2).max(30),legalName:z.string().trim().min(2).max(180),commercialName:z.string().trim().optional().nullable(),taxId:z.string().trim().optional().nullable(),contactName:z.string().trim().optional().nullable(),email:z.string().trim().email().optional().or(z.literal('')).nullable(),phone:z.string().trim().optional().nullable(),address:z.string().trim().optional().nullable(),creditDays:z.coerce.number().int().min(0).max(365).default(0),creditLimit:z.coerce.number().min(0).default(0),active:z.boolean().optional().default(true)});
router.get('/',requirePermission('customers.read'),async(req,res,next)=>{try{const customers=await prisma.customer.findMany({where:{companyId:req.auth.companyId},orderBy:[{active:'desc'},{legalName:'asc'}]});res.json({ok:true,customers})}catch(e){next(e)}});
router.post('/',requirePermission('customers.manage'),async(req,res,next)=>{try{const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({ok:false,message:p.error.issues[0]?.message??'Datos inválidos'});const customer=await prisma.customer.create({data:{...p.data,code:p.data.code.toUpperCase(),email:p.data.email||null,companyId:req.auth.companyId}});await prisma.auditLog.create({data:{userId:req.auth.sub,action:'CREATE',entity:'Customer',entityId:customer.id,description:`Cliente ${customer.code} creado`,ipAddress:req.ip}});emitIntegrationEventAsync({companyId:req.auth.companyId,event:'customer.created',entityType:'Customer',entityId:customer.id,payload:{customer}});await syncBusinessParties(req.auth.companyId);res.status(201).json({ok:true,customer})}catch(e){if(e.code==='P2002')return res.status(409).json({ok:false,message:'Ya existe un cliente con ese código'});next(e)}});
router.put('/:id',requirePermission('customers.manage'),async(req,res,next)=>{try{const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({ok:false,message:p.error.issues[0]?.message??'Datos inválidos'});const exists=await prisma.customer.findFirst({where:{id:req.params.id,companyId:req.auth.companyId}});if(!exists)return res.status(404).json({ok:false,message:'Cliente no encontrado'});const customer=await prisma.customer.update({where:{id:exists.id},data:{...p.data,code:p.data.code.toUpperCase(),email:p.data.email||null}});emitIntegrationEventAsync({companyId:req.auth.companyId,event:'customer.updated',entityType:'Customer',entityId:customer.id,payload:{customer}});await syncBusinessParties(req.auth.companyId);res.json({ok:true,customer})}catch(e){if(e.code==='P2002')return res.status(409).json({ok:false,message:'Ya existe un cliente con ese código'});next(e)}});
router.patch('/:id/status',requirePermission('customers.manage'),async(req,res,next)=>{try{const p=z.object({active:z.boolean()}).safeParse(req.body);if(!p.success)return res.status(400).json({ok:false,message:'Estado inválido'});const exists=await prisma.customer.findFirst({where:{id:req.params.id,companyId:req.auth.companyId}});if(!exists)return res.status(404).json({ok:false,message:'Cliente no encontrado'});const customer=await prisma.customer.update({where:{id:exists.id},data:{active:p.data.active}});await syncBusinessParties(req.auth.companyId);res.json({ok:true,customer})}catch(e){next(e)}});
export default router;
