import {Router} from 'express';
import {z} from 'zod';
import {prisma} from '../lib/prisma.js';
import {requireAuth} from '../middleware/auth.js';
import {requirePermission} from '../middleware/permissions.js';

const router=Router();router.use(requireAuth);
const attendanceSchema=z.object({employeeId:z.string().cuid(),date:z.coerce.date(),checkIn:z.coerce.date().optional().nullable(),checkOut:z.coerce.date().optional().nullable(),status:z.enum(['PRESENT','LATE','ABSENT','REMOTE','DAY_OFF']),notes:z.string().trim().optional().nullable()});
const leaveSchema=z.object({employeeId:z.string().cuid(),type:z.enum(['VACATION','PERSONAL','MEDICAL','MATERNITY','PATERNITY','UNPAID','OTHER']),startDate:z.coerce.date(),endDate:z.coerce.date(),days:z.coerce.number().positive(),reason:z.string().trim().optional().nullable()});
const incidentSchema=z.object({employeeId:z.string().cuid(),type:z.enum(['ABSENCE','LATE_ARRIVAL','OVERTIME','DISCIPLINARY','ACCIDENT','BONUS','DEDUCTION','OTHER']),date:z.coerce.date(),amount:z.coerce.number().min(0).optional().nullable(),description:z.string().trim().min(3),notes:z.string().trim().optional().nullable()});
async function employee(req,id){return prisma.employee.findFirst({where:{id,companyId:req.auth.companyId}})}
async function audit(req,action,entity,id,description){await prisma.auditLog.create({data:{userId:req.auth.sub,action,entity,entityId:id,description,ipAddress:req.ip}})}

router.get('/',requirePermission('attendance.read'),async(req,res,next)=>{try{const [employees,attendance,leaves,incidents]=await Promise.all([
 prisma.employee.findMany({where:{companyId:req.auth.companyId,status:{not:'TERMINATED'}},select:{id:true,employeeNumber:true,firstName:true,lastName:true},orderBy:{lastName:'asc'}}),
 prisma.attendanceRecord.findMany({where:{companyId:req.auth.companyId},include:{employee:true},orderBy:{date:'desc'},take:250}),
 prisma.leaveRequest.findMany({where:{companyId:req.auth.companyId},include:{employee:true},orderBy:{createdAt:'desc'},take:250}),
 prisma.hrIncident.findMany({where:{companyId:req.auth.companyId},include:{employee:true},orderBy:{date:'desc'},take:250})]);res.json({ok:true,employees,attendance,leaves,incidents})}catch(e){next(e)}});

router.post('/attendance',requirePermission('attendance.manage'),async(req,res,next)=>{try{const p=attendanceSchema.safeParse(req.body);if(!p.success)return res.status(400).json({ok:false,message:p.error.issues[0]?.message||'Datos inválidos'});if(!await employee(req,p.data.employeeId))return res.status(404).json({ok:false,message:'Empleado no encontrado'});const day=new Date(p.data.date);day.setHours(0,0,0,0);const record=await prisma.attendanceRecord.upsert({where:{employeeId_date:{employeeId:p.data.employeeId,date:day}},update:{...p.data,date:day},create:{...p.data,date:day,companyId:req.auth.companyId}});await audit(req,'UPSERT','AttendanceRecord',record.id,'Asistencia registrada');res.status(201).json({ok:true,record})}catch(e){next(e)}});
router.post('/leaves',requirePermission('leave_requests.manage'),async(req,res,next)=>{try{const p=leaveSchema.safeParse(req.body);if(!p.success)return res.status(400).json({ok:false,message:p.error.issues[0]?.message||'Datos inválidos'});if(p.data.endDate<p.data.startDate)return res.status(400).json({ok:false,message:'La fecha final no puede ser anterior'});if(!await employee(req,p.data.employeeId))return res.status(404).json({ok:false,message:'Empleado no encontrado'});const leave=await prisma.leaveRequest.create({data:{...p.data,companyId:req.auth.companyId}});await audit(req,'CREATE','LeaveRequest',leave.id,'Solicitud de ausencia creada');res.status(201).json({ok:true,leave})}catch(e){next(e)}});
router.patch('/leaves/:id/status',requirePermission('leave_requests.manage'),async(req,res,next)=>{try{const p=z.object({status:z.enum(['APPROVED','REJECTED','CANCELLED']),resolution:z.string().trim().optional().nullable()}).safeParse(req.body);if(!p.success)return res.status(400).json({ok:false,message:'Resolución inválida'});const found=await prisma.leaveRequest.findFirst({where:{id:req.params.id,companyId:req.auth.companyId}});if(!found)return res.status(404).json({ok:false,message:'Solicitud no encontrada'});const leave=await prisma.leaveRequest.update({where:{id:found.id},data:{...p.data,resolvedAt:new Date()}});await audit(req,'STATUS','LeaveRequest',leave.id,`Solicitud ${leave.status}`);res.json({ok:true,leave})}catch(e){next(e)}});
router.post('/incidents',requirePermission('hr_incidents.manage'),async(req,res,next)=>{try{const p=incidentSchema.safeParse(req.body);if(!p.success)return res.status(400).json({ok:false,message:p.error.issues[0]?.message||'Datos inválidos'});if(!await employee(req,p.data.employeeId))return res.status(404).json({ok:false,message:'Empleado no encontrado'});const incident=await prisma.hrIncident.create({data:{...p.data,companyId:req.auth.companyId}});await audit(req,'CREATE','HrIncident',incident.id,'Incidencia de RH creada');res.status(201).json({ok:true,incident})}catch(e){next(e)}});
export default router;
