import {Link,useLoaderData,useNavigation,useSearchParams} from 'react-router';
import {useRef} from 'react';
import {Money,getPaginationVariables} from '@shopify/hydrogen';
import {buildOrderSearchQuery,parseOrderFilters,ORDER_FILTER_FIELDS} from '~/lib/orderFilters';
import {CUSTOMER_ORDERS_QUERY} from '~/graphql/customer-account/CustomerOrdersQuery';
import {PaginatedResourceSection} from '~/components/PaginatedResourceSection';
import styles from '~/styles/Account.module.css';

export const meta=()=>[{title:'Pedidos | Essenze'}];
export async function loader({request,context}){const {customerAccount}=context;const paginationVariables=getPaginationVariables(request,{pageBy:12});const url=new URL(request.url);const filters=parseOrderFilters(url.searchParams);const query=buildOrderSearchQuery(filters);const {data,errors}=await customerAccount.query(CUSTOMER_ORDERS_QUERY,{variables:{...paginationVariables,query,language:customerAccount.i18n.language}});if(errors?.length||!data?.customer)throw Error('No fue posible cargar tus pedidos');return {customer:data.customer,filters};}

export default function Orders(){const {customer,filters}=useLoaderData();const {orders}=customer;return <section><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Historial de compra</p><h2>Mis pedidos</h2></div><p>Consulta tus compras anteriores o encuentra un pedido por número y confirmación.</p></div><OrderSearchForm currentFilters={filters}/>{orders.nodes.length?<PaginatedResourceSection connection={orders} resourcesClassName={styles.orderGrid}>{({node:order})=><OrderItem order={order}/>}</PaginatedResourceSection>:<div className={styles.empty}><h3>No encontramos pedidos.</h3><p>{filters.name||filters.confirmationNumber?'Prueba eliminando los filtros de búsqueda.':'Tu historial aparecerá aquí después de realizar una compra.'}</p><Link className={styles.statusLink} to="/collections/all">Explorar fragancias</Link></div>}</section>;}

function OrderSearchForm({currentFilters}){const [searchParams,setSearchParams]=useSearchParams();const navigation=useNavigation();const isSearching=navigation.state!=='idle'&&navigation.location?.pathname?.includes('orders');const formRef=useRef(null);const handleSubmit=(event)=>{event.preventDefault();const formData=new FormData(event.currentTarget);const params=new URLSearchParams();const name=formData.get(ORDER_FILTER_FIELDS.NAME)?.toString().trim();const confirmation=formData.get(ORDER_FILTER_FIELDS.CONFIRMATION_NUMBER)?.toString().trim();if(name)params.set(ORDER_FILTER_FIELDS.NAME,name);if(confirmation)params.set(ORDER_FILTER_FIELDS.CONFIRMATION_NUMBER,confirmation);setSearchParams(params);};const hasFilters=currentFilters.name||currentFilters.confirmationNumber;return <form ref={formRef} onSubmit={handleSubmit} className={styles.orderSearch} aria-label="Buscar pedidos"><fieldset><input type="search" name={ORDER_FILTER_FIELDS.NAME} placeholder="Número de pedido" aria-label="Número de pedido" defaultValue={currentFilters.name||''}/><input type="search" name={ORDER_FILTER_FIELDS.CONFIRMATION_NUMBER} placeholder="Número de confirmación" aria-label="Número de confirmación" defaultValue={currentFilters.confirmationNumber||''}/><button type="submit" disabled={isSearching}>{isSearching?'Buscando…':'Buscar'}</button>{hasFilters?<button className={styles.secondaryButton} type="button" disabled={isSearching} onClick={()=>{setSearchParams(new URLSearchParams());formRef.current?.reset();}}>Limpiar</button>:null}</fieldset></form>;}

function OrderItem({order}){const date=new Intl.DateTimeFormat('es-MX',{year:'numeric',month:'short',day:'numeric'}).format(new Date(order.processedAt));const fulfillment=translateStatus(order.fulfillmentStatus||order.fulfillments?.nodes?.[0]?.status);return <article className={styles.orderCard}><div className={styles.orderCardTop}><div><Link className={styles.orderNumber} to={`/account/orders/${btoa(order.id)}`}>Pedido #{order.number}</Link><p className={styles.date}>{date}{order.confirmationNumber?` · Conf. ${order.confirmationNumber}`:''}</p></div><div className={styles.pills}>{order.financialStatus?<span className={styles.pill}>{translateStatus(order.financialStatus)}</span>:null}{fulfillment?<span className={styles.pill}>{fulfillment}</span>:null}</div></div><div className={styles.orderCardBottom}><div><p className={styles.date}>Total</p><div className={styles.orderTotal}><Money data={order.totalPrice}/></div></div><Link className={styles.orderLink} to={`/account/orders/${btoa(order.id)}`}>Ver detalle →</Link></div></article>;}
function translateStatus(value){if(!value)return '';const key=String(value).toUpperCase();return {PAID:'Pagado',PENDING:'Pendiente',REFUNDED:'Reembolsado',PARTIALLY_REFUNDED:'Reembolso parcial',FULFILLED:'Enviado',UNFULFILLED:'Por preparar',IN_PROGRESS:'En proceso',ON_HOLD:'En espera',SCHEDULED:'Programado',OPEN:'Abierto',SUCCESS:'Completado'}[key]||String(value).replaceAll('_',' ').toLowerCase();}
/** @typedef {import('./+types/account.orders._index').Route} Route */
