import {Link,redirect,useLoaderData} from 'react-router';
import {Money,Image} from '@shopify/hydrogen';
import {CUSTOMER_ORDER_QUERY} from '~/graphql/customer-account/CustomerOrderQuery';
import styles from '~/styles/Account.module.css';

export const meta=({data})=>[{title:`${data?.order?.name||'Pedido'} | Essenze`}];
export async function loader({params,context}){const {customerAccount}=context;if(!params.id)return redirect('/account/orders');const orderId=atob(params.id);const {data,errors}=await customerAccount.query(CUSTOMER_ORDER_QUERY,{variables:{orderId,language:customerAccount.i18n.language}});if(errors?.length||!data?.order)throw new Error('Pedido no encontrado');const {order}=data;const lineItems=order.lineItems.nodes;const firstDiscount=order.discountApplications.nodes[0]?.value;return {order,lineItems,discountValue:firstDiscount?.__typename==='MoneyV2'?firstDiscount:null,discountPercentage:firstDiscount?.__typename==='PricingPercentageValue'?firstDiscount.percentage:null,fulfillmentStatus:order.fulfillments.nodes[0]?.status??order.fulfillmentStatus??'N/A'};}
export default function OrderRoute(){const {order,lineItems,discountValue,discountPercentage,fulfillmentStatus}=useLoaderData();const date=new Intl.DateTimeFormat('es-MX',{year:'numeric',month:'long',day:'numeric'}).format(new Date(order.processedAt));return <section><Link className={styles.eyebrow} to="/account/orders">← Mis pedidos</Link><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>Detalle de compra</p><h2>{order.name}</h2></div><p>Realizado el {date}{order.confirmationNumber?` · Confirmación ${order.confirmationNumber}`:''}</p></div><div className={styles.tableWrap}><table className={styles.orderTable}><thead><tr><th>Producto</th><th>Precio</th><th>Cant.</th><th>Total</th></tr></thead><tbody>{lineItems.map((lineItem)=><OrderLineRow key={lineItem.id} lineItem={lineItem}/>)}</tbody></table></div><div className={styles.summary}><div className={styles.summaryCard}><span>Subtotal</span><strong><Money data={order.subtotal}/></strong></div><div className={styles.summaryCard}><span>Impuestos</span><strong>{order.totalTax?<Money data={order.totalTax}/>: '—'}</strong></div><div className={styles.summaryCard}><span>Total</span><strong><Money data={order.totalPrice}/></strong></div>{discountPercentage||discountValue?<div className={styles.summaryCard}><span>Descuento</span><strong>{discountPercentage?`-${discountPercentage}%`:<Money data={discountValue}/>}</strong></div>:null}</div><div className={styles.infoGrid}><div className={styles.infoCard}><h3>Dirección de envío</h3>{order.shippingAddress?<address><p>{order.shippingAddress.formatted?.join?.('\n')||order.shippingAddress.formatted||order.shippingAddress.formattedArea}</p></address>:<p>Sin dirección de envío.</p>}</div><div className={styles.infoCard}><h3>Estado</h3><p>{translateStatus(fulfillmentStatus)}</p>{order.statusPageUrl?<a className={styles.statusLink} target="_blank" href={order.statusPageUrl} rel="noreferrer">Ver estado en Shopify ↗</a>:null}</div></div></section>;}
function OrderLineRow({lineItem}){const amount=Number(lineItem.price?.amount||0)*Number(lineItem.quantity||0)-Number(lineItem.totalDiscount?.amount||0);const total={amount:String(Math.max(amount,0)),currencyCode:lineItem.price?.currencyCode};return <tr><td><div className={styles.lineProduct}>{lineItem.image?<Image data={lineItem.image} width={70} height={82}/>:null}<div><strong>{lineItem.title}</strong>{lineItem.variantTitle?<small>{lineItem.variantTitle}</small>:null}</div></div></td><td><Money data={lineItem.price}/></td><td>{lineItem.quantity}</td><td><Money data={total}/></td></tr>;}
function translateStatus(value){if(!value)return 'No especificado';const key=String(value).toUpperCase();return {FULFILLED:'Enviado',UNFULFILLED:'Por preparar',IN_PROGRESS:'En proceso',ON_HOLD:'En espera',SUCCESS:'Completado'}[key]||String(value).replaceAll('_',' ').toLowerCase();}
/** @typedef {import('./+types/account.orders.$id').Route} Route */
