import {data as remixData,Form,NavLink,Outlet,useLoaderData} from 'react-router';
import {CUSTOMER_DETAILS_QUERY} from '~/graphql/customer-account/CustomerDetailsQuery';
import styles from '~/styles/Account.module.css';
export function shouldRevalidate(){return true;}
export async function loader({context}){const {customerAccount}=context;const {data,errors}=await customerAccount.query(CUSTOMER_DETAILS_QUERY,{variables:{language:customerAccount.i18n.language}});if(errors?.length||!data?.customer)throw new Error('Customer not found');return remixData({customer:data.customer},{headers:{'Cache-Control':'no-cache, no-store, must-revalidate'}});}
export default function AccountLayout(){const {customer}=useLoaderData();const name=customer?.firstName?`, ${customer.firstName}`:'';return <main className={styles.page}><section className={styles.hero}><div className={styles.heroInner}><p className={styles.eyebrow}>Private client</p><h1>Bienvenido{name}.</h1><p>Administra tus pedidos, información personal y direcciones desde un espacio simple y privado.</p></div></section><div className={styles.layout}><div className={styles.sidebar}><AccountMenu/></div><div className={styles.content}><Outlet context={{customer}}/></div></div></main>;}
function AccountMenu(){return <nav className={styles.nav} aria-label="Mi cuenta"><NavLink to="/account/orders" className={({isActive})=>`${styles.navLink} ${isActive?styles.navLinkActive:''}`}>Pedidos</NavLink><NavLink to="/account/profile" className={({isActive})=>`${styles.navLink} ${isActive?styles.navLinkActive:''}`}>Perfil</NavLink><NavLink to="/account/addresses" className={({isActive})=>`${styles.navLink} ${isActive?styles.navLinkActive:''}`}>Direcciones</NavLink><Logout/></nav>;}
function Logout(){return <Form className={styles.logout} method="POST" action="/account/logout"><button type="submit">Cerrar sesión</button></Form>;}
/** @typedef {import('./+types/account').Route} Route */
