import {Check, ChevronRight, PackageCheck, Plus, Search, Send, X} from 'lucide-react';
import {useEffect, useMemo, useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {apiRequest} from '../api';
import {Badge, Button, Card, Input} from '../design-system/components';
import styles from './PurchaseOrders.module.css';

import KpiInfo from '../components/KpiInfo';
import KpiCard from '../components/KpiCard';
const statusMap={DRAFT:['Borrador','neutral'],ISSUED:['Emitida','info'],PARTIALLY_RECEIVED:['Recepción parcial','warning'],RECEIVED:['Recibida','success'],CANCELLED:['Cancelada','danger']};
const money=(value,currency='MXN')=>Number(value||0).toLocaleString('es-MX',{style:'currency',currency});
const blankItem=()=>({productId:'',quantity:1,unitCost:0,taxRate:16,notes:''});
const blankForm=()=>({supplierId:'',warehouseId:'',purchaseRequestId:'',expectedDate:'',paymentTerms:0,currency:'MXN',notes:'',items:[blankItem()]});

export default function PurchaseOrders(){
  const navigate=useNavigate();
  const [orders,setOrders]=useState([]),[suppliers,setSuppliers]=useState([]),[warehouses,setWarehouses]=useState([]),[approvedRequests,setApprovedRequests]=useState([]),[products,setProducts]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[query,setQuery]=useState(''),[form,setForm]=useState(null),[detail,setDetail]=useState(null),[message,setMessage]=useState(null);
  async function load(){setLoading(true);try{const data=await apiRequest('/purchase-orders');setOrders(data.orders||[]);setSuppliers(data.suppliers||[]);setWarehouses(data.warehouses||[]);setApprovedRequests(data.approvedRequests||[]);setProducts(data.products||[]);}catch(error){setMessage({type:'error',text:error.message});}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  const filtered=useMemo(()=>{const q=query.toLowerCase().trim();return q?orders.filter(o=>[o.folio,o.supplier?.legalName,o.status,o.purchaseRequest?.folio].filter(Boolean).join(' ').toLowerCase().includes(q)):orders;},[orders,query]);
  const metrics={total:orders.length,drafts:orders.filter(o=>o.status==='DRAFT').length,pending:orders.filter(o=>['ISSUED','PARTIALLY_RECEIVED'].includes(o.status)).length,value:orders.reduce((s,o)=>s+Number(o.total),0)};
  function openCreate(){const f=blankForm();f.supplierId=suppliers[0]?.id||'';f.warehouseId=warehouses[0]?.id||'';setForm(f);}
  function fromRequest(id){const r=approvedRequests.find(x=>x.id===id);setForm(v=>({...v,purchaseRequestId:id,warehouseId:r?.warehouseId||v.warehouseId,items:r?.items?.map(i=>({productId:i.productId,quantity:Number(i.quantity),unitCost:Number(i.estimatedUnitCost),taxRate:16,notes:i.notes||''}))||[blankItem()]}));}
  function updateItem(index,key,value){setForm(v=>({...v,items:v.items.map((item,i)=>i===index?{...item,[key]:value}:item)}));}
  function selectProduct(index,id){const p=products.find(x=>x.id===id);setForm(v=>({...v,items:v.items.map((item,i)=>i===index?{...item,productId:id,unitCost:p?Number(p.cost):0}:item)}));}
  function addItem(){setForm(v=>({...v,items:[...v.items,blankItem()]}));}
  function removeItem(index){setForm(v=>({...v,items:v.items.filter((_,i)=>i!==index)}));}
  async function save(e){e.preventDefault();setSaving(true);try{await apiRequest('/purchase-orders',{method:'POST',body:{...form,paymentTerms:Number(form.paymentTerms),items:form.items.map(i=>({...i,quantity:Number(i.quantity),unitCost:Number(i.unitCost),taxRate:Number(i.taxRate)}))}});setForm(null);await load();setMessage({type:'success',text:'Orden de compra creada.'});}catch(error){setMessage({type:'error',text:error.message});}finally{setSaving(false);}}
  async function issue(id){try{await apiRequest(`/purchase-orders/${id}/issue`,{method:'POST'});setDetail(null);await load();setMessage({type:'success',text:'Orden emitida al proveedor.'});}catch(error){setMessage({type:'error',text:error.message});}}
  function receive(order){setDetail(null);navigate(`/compras/recepciones?order=${order.id}`);}
  if(loading)return <div className={styles.loading}>Cargando órdenes…</div>;
  return <div className={styles.page}>
    <header className={styles.header}><div><span className={styles.eyebrow}>Compras</span><h1>Órdenes de compra</h1><p>Convierte solicitudes aprobadas en órdenes formales y controla su recepción.</p></div><Button icon={Plus} onClick={openCreate}>Nueva orden</Button></header>
    {message?<div className={`${styles.message} ${styles[message.type]}`}>{message.text}</div>:null}
    <section className={styles.metrics}><KpiCard><span>Total órdenes</span><KpiInfo title="\u00d3rdenes registradas">Cantidad total de órdenes de compra.</KpiInfo><strong>{metrics.total}</strong></KpiCard><KpiCard><span>Borradores</span><KpiInfo title="\u00d3rdenes en preparaci\u00f3n">Órdenes todavía editables y no confirmadas.</KpiInfo><strong>{metrics.drafts}</strong></KpiCard><KpiCard><span>Por recibir</span><KpiInfo title="\u00d3rdenes pendientes">Órdenes con mercancía pendiente de recepción.</KpiInfo><strong>{metrics.pending}</strong></KpiCard><KpiCard><span>Valor ordenado</span><KpiInfo title="Compras ordenadas">Importe acumulado de las órdenes de compra.</KpiInfo><strong>{money(metrics.value)}</strong></KpiCard></section>
    <Card className={styles.tableCard}><div className={styles.toolbar}><div><h2>Control de órdenes</h2><p>{filtered.length} registros</p></div><label className={styles.search}><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar folio, proveedor o solicitud"/></label></div><div className={styles.tableWrap}><table><thead><tr><th>Folio</th><th>Proveedor</th><th>Solicitud</th><th>Almacén</th><th>Total</th><th>Estado</th><th></th></tr></thead><tbody>{filtered.map(o=>{const status=statusMap[o.status]||[o.status,'neutral'];return <tr key={o.id}><td><strong>{o.folio}</strong><small>{new Date(o.orderDate).toLocaleDateString('es-MX')}</small></td><td><strong>{o.supplier?.commercialName||o.supplier?.legalName}</strong><small>{o.supplier?.code}</small></td><td>{o.purchaseRequest?.folio||'Directa'}</td><td>{o.warehouse?.name}<small>{o.warehouse?.branch?.name}</small></td><td>{money(o.total,o.currency)}</td><td><Badge tone={status[1]}>{status[0]}</Badge></td><td><button className={styles.detailButton} onClick={()=>setDetail(o)}>Ver <ChevronRight size={16}/></button></td></tr>})}</tbody></table>{!filtered.length?<div className={styles.empty}>No hay órdenes registradas.</div>:null}</div></Card>
    {form?<div className={styles.overlay}><form className={styles.modal} onSubmit={save}><div className={styles.modalHeader}><div><span>Nueva orden</span><h2>Datos de compra</h2></div><button type="button" onClick={()=>setForm(null)}><X/></button></div><div className={styles.modalBody}>
      <div className={styles.grid2}><label><span>Solicitud aprobada</span><select value={form.purchaseRequestId} onChange={e=>fromRequest(e.target.value)}><option value="">Orden directa</option>{approvedRequests.map(r=><option key={r.id} value={r.id}>{r.folio} · {r.title}</option>)}</select></label><label><span>Proveedor</span><select required value={form.supplierId} onChange={e=>setForm(v=>({...v,supplierId:e.target.value}))}><option value="">Selecciona</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.code} · {s.commercialName||s.legalName}</option>)}</select></label></div>
      <div className={styles.grid3}><label><span>Almacén destino</span><select required value={form.warehouseId} onChange={e=>setForm(v=>({...v,warehouseId:e.target.value}))}><option value="">Selecciona</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.name} · {w.branch?.name}</option>)}</select></label><Input label="Fecha esperada" type="date" value={form.expectedDate} onChange={e=>setForm(v=>({...v,expectedDate:e.target.value}))}/><Input label="Días de crédito" type="number" min="0" value={form.paymentTerms} onChange={e=>setForm(v=>({...v,paymentTerms:e.target.value}))}/></div>
      <label><span>Notas y condiciones</span><textarea rows="3" value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))}/></label>
      <div className={styles.itemsHeader}><div><h3>Partidas</h3><p>Define cantidades, costos e impuestos.</p></div><Button type="button" variant="secondary" icon={Plus} onClick={addItem}>Agregar</Button></div>
      <div className={styles.items}>{form.items.map((i,index)=><div className={styles.item} key={index}><label className={styles.product}><span>Producto</span><select required value={i.productId} onChange={e=>selectProduct(index,e.target.value)}><option value="">Selecciona</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} · {p.name}</option>)}</select></label><Input label="Cantidad" type="number" min="0.001" step="0.001" value={i.quantity} onChange={e=>updateItem(index,'quantity',e.target.value)}/><Input label="Costo" type="number" min="0" step="0.01" value={i.unitCost} onChange={e=>updateItem(index,'unitCost',e.target.value)}/><Input label="IVA %" type="number" min="0" max="100" value={i.taxRate} onChange={e=>updateItem(index,'taxRate',e.target.value)}/><button type="button" className={styles.remove} disabled={form.items.length===1} onClick={()=>removeItem(index)}><X size={18}/></button></div>)}</div>
    </div><div className={styles.modalFooter}><Button type="button" variant="ghost" onClick={()=>setForm(null)}>Cancelar</Button><Button type="submit" loading={saving}>Crear orden</Button></div></form></div>:null}
    {detail?<div className={styles.overlay}><div className={styles.drawer}><div className={styles.modalHeader}><div><span>{detail.folio}</span><h2>{detail.supplier?.commercialName||detail.supplier?.legalName}</h2></div><button onClick={()=>setDetail(null)}><X/></button></div><div className={styles.detailBody}><div className={styles.detailGrid}><div><span>Estado</span><Badge tone={(statusMap[detail.status]||[])[1]}>{(statusMap[detail.status]||[])[0]}</Badge></div><div><span>Total</span><strong>{money(detail.total,detail.currency)}</strong></div><div><span>Crédito</span><strong>{detail.paymentTerms} días</strong></div><div><span>Entrega</span><strong>{detail.expectedDate?new Date(detail.expectedDate).toLocaleDateString('es-MX'):'Sin fecha'}</strong></div></div><span className={styles.label}>Partidas</span>{detail.items.map(i=><div className={styles.detailItem} key={i.id}><div><strong>{i.product?.name}</strong><small>{i.product?.sku} · {i.quantity} {i.product?.unit} · recibido {i.receivedQuantity}</small></div><strong>{money(i.total,detail.currency)}</strong></div>)}</div><div className={styles.modalFooter}>{detail.status==='DRAFT'?<Button icon={Send} onClick={()=>issue(detail.id)}>Emitir orden</Button>:null}{['ISSUED','PARTIALLY_RECEIVED'].includes(detail.status)?<Button icon={PackageCheck} onClick={()=>receive(detail)}>Recibir pendiente</Button>:null}{detail.status==='RECEIVED'?<Button variant="secondary" icon={Check}>Recepción completa</Button>:null}</div></div></div>:null}
  </div>;
}
